# Site settings
title: Jorge Agúndez | Junior Developer
email: jamedina97@gmail.com
description: "Junior Developer Jorge Agundez Medina"
baseurl: ""
url: "http://www.jorgeagundez.com"
twitter_username: JorgeAgundez
github_username:  jorgeagundez

# Build settings
markdown: kramdown
permalink: pretty
